In [1]:
import pandas as pd
data_3 = pd.read_csv("C:/Users/lydia/Documents/Datascientest/Projet fil rouge/CSV_files/data_3.csv")

In [2]:
display(data_3)

,Mh,Mt,Ewltp (g/km),W (mm),At1 (mm),Ft,ec (cm3),ep (KW),IT,Erwltp (g/km),Fuel consumption,Ct_M1,Ct_M1G,Ct_N1,Ct_N1G,Country_DE,Country_FR
0,54,1076.0,117.0,2492.0,1455.0,5,999.0,48.0,83,1.09,5.2,1.0,0.0,0.0,0.0,0.0,1.0
1,54,1077.0,117.0,2492.0,1455.0,5,999.0,48.0,83,1.09,5.2,1.0,0.0,0.0,0.0,0.0,1.0
2,54,1077.0,117.0,2492.0,1455.0,5,999.0,48.0,83,1.09,5.2,1.0,0.0,0.0,0.0,0.0,1.0
3,54,1077.0,117.0,2492.0,1455.0,5,999.0,48.0,83,1.09,5.2,1.0,0.0,0.0,0.0,0.0,1.0
4,54,1071.0,117.0,2492.0,1455.0,5,999.0,48.0,83,1.09,5.2,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3528579,48,1062.0,113.0,2450.0,1430.0,5,1193.0,52.0,2,0.78,5.0,1.0,0.0,0.0,0.0,1.0,0.0
3528580,48,1091.0,125.0,2450.0,1430.0,5,1193.0,52.0,2,0.78,5.5,1.0,0.0,0.0,0.0,1.0,0.0
3528581,48,1091.0,125.0,2450.0,1430.0,5,1193.0,52.0,2,0.78,5.5,1.0,0.0,0.0,0.0,1.0,0.0
3528582,48,1091.0,125.0,2450.0,1430.0,5,1193.0,52.0,2,0.78,5.5,1.0,0.0,0.0,0.0,1.0,0.0
3528583,48,1091.0,125.0,2450.0,1430.0,5,1193.0,52.0,2,0.78,5.5,1.0,0.0,0.0,0.0,1.0,0.0

In [5]:
data_3.columns

Index(['Mh', 'Mt', 'Ewltp (g/km)', 'W (mm)', 'At1 (mm)', 'Ft', 'ec (cm3)',
       'ep (KW)', 'IT', 'Erwltp (g/km)', 'Fuel consumption ', 'Ct_M1',
       'Ct_M1G', 'Ct_N1', 'Ct_N1G', 'Country_DE', 'Country_FR'],
      dtype='object')

In [6]:
data_3.isna().sum()

Mh                   0
Mt                   0
Ewltp (g/km)         0
W (mm)               0
At1 (mm)             0
Ft                   0
ec (cm3)             0
ep (KW)              0
IT                   0
Erwltp (g/km)        0
Fuel consumption     0
Ct_M1                0
Ct_M1G               0
Ct_N1                0
Ct_N1G               0
Country_DE           0
Country_FR           0
dtype: int64

In [2]:
data_3['Labels_Ewltp'] = data_3['Ewltp (g/km)'].apply(lambda x: 'A' if x <= 100 else ('B' if x <= 120 else ('C' if x <= 140 else ('D' if x <= 160 else ('E' if x <= 200 else ('F' if x <= 250 else ('G' if x > 250 else None)))))))
print(data_3)

         Mh      Mt  Ewltp (g/km)  W (mm)  At1 (mm)  Ft  ec (cm3)  ep (KW)  \
0        54  1076.0         117.0  2492.0    1455.0   5     999.0     48.0
1        54  1077.0         117.0  2492.0    1455.0   5     999.0     48.0
2        54  1077.0         117.0  2492.0    1455.0   5     999.0     48.0
3        54  1077.0         117.0  2492.0    1455.0   5     999.0     48.0
4        54  1071.0         117.0  2492.0    1455.0   5     999.0     48.0
...      ..     ...           ...     ...       ...  ..       ...      ...
3528579  48  1062.0         113.0  2450.0    1430.0   5    1193.0     52.0
3528580  48  1091.0         125.0  2450.0    1430.0   5    1193.0     52.0
3528581  48  1091.0         125.0  2450.0    1430.0   5    1193.0     52.0
3528582  48  1091.0         125.0  2450.0    1430.0   5    1193.0     52.0
3528583  48  1091.0         125.0  2450.0    1430.0   5    1193.0     52.0

         IT  Erwltp (g/km)  Fuel consumption   Ct_M1  Ct_M1G  Ct_N1  Ct_N1G  \
0        83           1.09                5.2    1.0     0.0    0.0     0.0
1        83           1.09                5.2    1.0     0.0    0.0     0.0
2        83           1.09                5.2    1.0     0.0    0.0     0.0
3        83           1.09                5.2    1.0     0.0    0.0     0.0
4        83           1.09                5.2    1.0     0.0    0.0     0.0
...      ..            ...                ...    ...     ...    ...     ...
3528579   2           0.78                5.0    1.0     0.0    0.0     0.0
3528580   2           0.78                5.5    1.0     0.0    0.0     0.0
3528581   2           0.78                5.5    1.0     0.0    0.0     0.0
3528582   2           0.78                5.5    1.0     0.0    0.0     0.0
3528583   2           0.78                5.5    1.0     0.0    0.0     0.0

         Country_DE  Country_FR Labels_Ewltp
0               0.0         1.0            B
1               0.0         1.0            B
2               0.0         1.0            B
3               0.0         1.0            B
4               0.0         1.0            B
...             ...         ...          ...
3528579         1.0         0.0            B
3528580         1.0         0.0            C
3528581         1.0         0.0            C
3528582         1.0         0.0            C
3528583         1.0         0.0            C

[3528584 rows x 18 columns]

In [14]:
data_3['Labels_Ewltp'].unique()

array(['B', 'C', 'D', 'E', 'A', 'G', 'F'], dtype=object)

In [3]:
to_drop_regression = ['Labels_Ewltp', 'Ewltp (g/km)']
data_3_regression = data_3.drop(to_drop_regression, axis=1)
target_regression = data_3['Ewltp (g/km)']

to_drop_classification = ['Labels_Ewltp', 'Ewltp (g/km)']
data_3_classification = data_3.drop(to_drop_classification, axis=1)
target_classification = data_3['Labels_Ewltp']

In [4]:
from sklearn.model_selection import train_test_split
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(data_3_regression, target_regression, test_size=0.20)
X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(data_3_classification, target_classification, test_size=0.20)

In [5]:
from sklearn.preprocessing import StandardScaler
cols_num = ['Mt', 'W (mm)', 'At1 (mm)', 'ec (cm3)', 'ep (KW)', 'Erwltp (g/km)', 'Fuel consumption ']

sc = StandardScaler()
X_train_r[cols_num] = sc.fit_transform(X_train_r[cols_num])
X_test_r[cols_num] = sc.transform(X_test_r[cols_num])

X_train_c[cols_num] = sc.fit_transform(X_train_c[cols_num])
X_test_c[cols_num] = sc.transform(X_test_c[cols_num])

In [6]:
display(X_train_r)
display(X_test_r)
display(X_train_c)
display(X_test_c)
display(y_train_r)
display(y_test_r)
display(y_train_c)
display(y_test_c)

,Mh,Mt,W (mm),At1 (mm),Ft,ec (cm3),ep (KW),IT,Erwltp (g/km),Fuel consumption,Ct_M1,Ct_M1G,Ct_N1,Ct_N1G,Country_DE,Country_FR
2345052,46,-0.435460,0.314295,0.288791,5,-0.479448,-0.197933,2,-0.782622,0.323709,1.0,0.0,0.0,0.0,0.0,1.0
473778,54,0.123830,0.231359,0.269874,5,-0.479448,-0.652183,28,0.990246,0.723503,1.0,0.0,0.0,0.0,0.0,1.0
163676,46,2.670446,3.319134,1.745402,0,0.640082,1.146648,2,-1.255386,1.223246,1.0,0.0,0.0,0.0,1.0,0.0
2855626,51,-0.668261,-0.483168,-1.186737,5,-0.720383,-0.543163,25,1.392096,0.223760,1.0,0.0,0.0,0.0,1.0,0.0
2597416,34,1.148722,0.008069,1.348144,2,0.725224,0.656058,70,1.344820,1.922885,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587534,16,-0.997589,-0.483168,-0.335471,3,-1.082690,-0.797543,85,0.399290,0.873426,1.0,0.0,0.0,0.0,0.0,1.0
1416177,40,-0.432621,-0.508687,-0.921899,5,-0.405175,-0.288783,56,1.463011,0.373683,1.0,0.0,0.0,0.0,1.0,0.0
3474134,69,0.802360,1.226592,0.875219,0,0.674501,0.619718,66,-0.688069,0.123812,1.0,0.0,0.0,0.0,1.0,0.0
1635332,61,0.944312,0.320674,0.894136,6,0.002421,0.401678,25,-0.000357,-1.975107,1.0,0.0,0.0,0.0,0.0,1.0
1102770,25,2.738583,1.615754,3.599270,0,0.721601,0.456188,63,-1.019004,1.173271,1.0,0.0,0.0,0.0,1.0,0.0

,Mh,Mt,W (mm),At1 (mm),Ft,ec (cm3),ep (KW),IT,Erwltp (g/km),Fuel consumption,Ct_M1,Ct_M1G,Ct_N1,Ct_N1G,Country_DE,Country_FR
2171707,33,-0.566056,-0.189702,0.099621,5,-1.084502,-0.415973,66,-1.066281,-0.026111,1.0,0.0,0.0,0.0,1.0,0.0
2815949,5,0.717189,-0.017450,0.534712,0,0.672690,0.656058,13,0.612034,0.673529,1.0,0.0,0.0,0.0,1.0,0.0
3175750,68,-0.282152,-0.068487,-0.959733,5,-0.178733,-0.270613,25,-0.000357,0.173786,1.0,0.0,0.0,0.0,1.0,0.0
2451367,68,-0.327577,-0.572484,-0.297637,5,-0.178733,-0.016233,11,-0.853536,0.523606,1.0,0.0,0.0,0.0,0.0,1.0
3324319,68,-0.733559,-0.821292,-0.865148,5,-1.082690,-0.543163,11,-0.948089,0.323709,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1218629,60,-0.364484,-0.349194,-0.316554,5,-0.178733,-0.016233,79,1.108437,0.423657,1.0,0.0,0.0,0.0,1.0,0.0
1655959,61,-0.659744,-0.062108,0.118538,5,-0.720383,-0.270613,25,1.344820,0.023863,1.0,0.0,0.0,0.0,0.0,1.0
2093074,42,-0.185625,-0.157803,0.213123,5,0.727036,-0.016233,9,-1.964534,0.273735,1.0,0.0,0.0,0.0,1.0,0.0
2829632,15,0.938633,-0.700078,-0.051716,6,-0.479448,-0.270613,25,-0.000357,-1.725236,1.0,0.0,0.0,0.0,0.0,1.0
3035828,5,0.612144,0.952265,0.080704,0,0.672690,0.710568,18,1.108437,0.173786,1.0,0.0,0.0,0.0,1.0,0.0

,Mh,Mt,W (mm),At1 (mm),Ft,ec (cm3),ep (KW),IT,Erwltp (g/km),Fuel consumption,Ct_M1,Ct_M1G,Ct_N1,Ct_N1G,Country_DE,Country_FR
2962450,61,-1.003130,-0.892136,-1.205844,5,-0.720429,-0.670537,25,1.439454,-0.076709,1.0,0.0,0.0,0.0,1.0,0.0
689018,16,-1.088297,-0.483549,-0.335539,5,-1.082782,-0.797766,21,0.824865,0.223280,1.0,0.0,0.0,0.0,0.0,1.0
479320,54,0.311278,0.231479,0.269890,5,-0.479463,-0.270677,28,0.824865,0.823259,1.0,0.0,0.0,0.0,0.0,1.0
3519584,62,-1.451675,-2.424339,-2.776177,5,-1.082782,-1.070398,48,-0.593416,-0.376699,1.0,0.0,0.0,0.0,1.0,0.0
2695285,36,0.135266,0.257015,0.364489,6,-0.030144,-0.616011,25,-0.000262,-2.276632,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221117,9,1.784664,3.800233,1.215874,0,0.725363,0.347290,29,-0.971624,0.923256,1.0,0.0,0.0,0.0,1.0,0.0
1490944,58,-0.318957,-0.375018,0.402328,5,-0.178709,-0.016220,82,1.013970,0.473271,1.0,0.0,0.0,0.0,0.0,1.0
701338,16,-1.318247,-0.483549,-0.335539,5,-1.082782,-1.124925,85,0.564847,-0.026711,1.0,0.0,0.0,0.0,0.0,1.0
3471681,69,0.152300,0.142100,0.894240,5,-0.216757,-0.288852,25,-0.000262,0.823259,1.0,0.0,0.0,0.0,1.0,0.0
1165008,54,0.044422,0.346394,0.913159,5,-0.479463,0.092833,28,0.848503,0.623266,1.0,0.0,0.0,0.0,1.0,0.0

,Mh,Mt,W (mm),At1 (mm),Ft,ec (cm3),ep (KW),IT,Erwltp (g/km),Fuel consumption,Ct_M1,Ct_M1G,Ct_N1,Ct_N1G,Country_DE,Country_FR
67702,5,-0.883897,-0.828295,-0.808531,5,-1.082782,-0.743239,13,1.013970,0.273278,1.0,0.0,0.0,0.0,0.0,1.0
690181,16,-1.020163,-0.483549,-0.335539,5,-1.082782,-0.797766,21,0.824865,0.223280,1.0,0.0,0.0,0.0,0.0,1.0
3153803,68,-0.208240,-0.387786,-0.959888,5,0.701810,0.529045,2,-0.924348,0.573268,1.0,0.0,0.0,0.0,1.0,0.0
267092,46,1.901058,1.655150,0.894240,1,0.640210,0.583572,25,-0.000262,-1.976642,1.0,0.0,0.0,0.0,1.0,0.0
1994951,65,-0.514840,-0.764453,-0.354459,5,0.038703,1.474171,74,-1.255280,1.423238,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2907273,11,0.847829,-0.062193,0.175292,6,-0.176898,-0.343378,25,-0.000262,-1.776649,1.0,0.0,0.0,0.0,1.0,0.0
3128600,68,0.271533,0.678371,-0.373379,5,-0.178709,-0.016220,3,0.872141,0.623266,1.0,0.0,0.0,0.0,1.0,0.0
3162975,68,0.157978,-0.323945,-0.903129,6,-0.365322,-0.016220,25,-0.000262,-2.176635,1.0,0.0,0.0,0.0,1.0,0.0
79040,5,-0.097523,-0.355865,-0.524736,0,0.672822,-0.016220,13,0.683037,-0.326700,1.0,0.0,0.0,0.0,1.0,0.0
1083025,25,2.536971,3.959838,3.221360,0,0.721740,-0.270677,63,-1.018900,1.273243,1.0,0.0,0.0,0.0,1.0,0.0

2345052    136.0
473778     154.0
163676     205.0
2855626    131.0
2597416    208.0
           ...
587534     109.0
1416177    139.0
3474134    147.0
1635332     32.0
1102770    201.0
Name: Ewltp (g/km), Length: 2822867, dtype: float64

2171707    119.0
2815949    176.0
3175750    128.0
2451367    145.0
3324319    137.0
           ...
1218629    140.0
1655959    122.0
2093074    134.0
2829632     44.0
3035828    149.0
Name: Ewltp (g/km), Length: 705717, dtype: float64

2962450    B
689018     C
479320     D
3519584    B
2695285    A
          ..
221117     E
1490944    D
701338     B
3471681    D
1165008    D
Name: Labels_Ewltp, Length: 2822867, dtype: object

67702      C
690181     C
3153803    D
267092     A
1994951    E
          ..
2907273    A
3128600    D
3162975    A
79040      C
1083025    F
Name: Labels_Ewltp, Length: 705717, dtype: object

In [7]:
#Classification _ Decision Tree
from sklearn.tree import DecisionTreeClassifier

dt_clf = DecisionTreeClassifier(random_state=123)
dt_clf.fit(X_train_c, y_train_c)

y_pred_c = dt_clf.predict(X_test_c)
pd.crosstab(y_test_c, y_pred_c, rownames=['Classe rÃ©elle'], colnames=['Classe prÃ©dite'])

Classe prÃ©dite       A       B       C       D      E      F     G
Classe rÃ©elle
A               112015       1       3       2      9      1     1
B                   11  134597     479       0      4      0     0
C                    8     586  241081     411     79     13    16
D                    9       0     615  119273    212      1     0
E                    5       0      39     287  62231    102     3
F                    9       0      50       1    115  25085    36
G                    2       0      52       0      3     33  8237

In [11]:
#Calculs des scores
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

accuracy = accuracy_score(y_test_c, y_pred_c)
print(f"Accuracy: {accuracy:.4f}")
print("/n")
precision = precision_score(y_test_c, y_pred_c, average='weighted')
print(f"Precision: {precision:.4f}")
print("/n")
recall = recall_score(y_test_c, y_pred_c, average='weighted')
print(f"Recall: {recall:.4f}")
print("/n")
f1 = f1_score(y_test_c, y_pred_c, average='weighted')
print(f"F1 Score: {f1:.4f}")
print("/n")
conf_matrix = confusion_matrix(y_test_c, y_pred_c)
print("Confusion Matrix:")
print(conf_matrix)
print("/n")
class_report = classification_report(y_test_c, y_pred_c)
print("Classification Report:")
print(class_report)

Accuracy: 0.9955
/n
Precision: 0.9955
/n
Recall: 0.9955
/n
F1 Score: 0.9955
/n
Confusion Matrix:
[[112015      1      3      2      9      1      1]
 [    11 134597    479      0      4      0      0]
 [     8    586 241081    411     79     13     16]
 [     9      0    615 119273    212      1      0]
 [     5      0     39    287  62231    102      3]
 [     9      0     50      1    115  25085     36]
 [     2      0     52      0      3     33   8237]]
/n
Classification Report:
              precision    recall  f1-score   support

           A       1.00      1.00      1.00    112032
           B       1.00      1.00      1.00    135091
           C       0.99      1.00      1.00    242194
           D       0.99      0.99      0.99    120110
           E       0.99      0.99      0.99     62667
           F       0.99      0.99      0.99     25296
           G       0.99      0.99      0.99      8327

    accuracy                           1.00    705717
   macro avg       0.99      0.99      0.99    705717
weighted avg       1.00      1.00      1.00    705717

In [9]:
#Feature importance
feats = {}
for feature, importance in zip(data_3.columns, dt_clf.feature_importances_):
    feats[feature] = importance 
    
importances = pd.DataFrame.from_dict(feats, orient='index').rename(columns={0: 'Importance'})
importances.sort_values(by='Importance', ascending=False)

                   Importance
Erwltp (g/km)        0.616740
At1 (mm)             0.207275
ec (cm3)             0.100996
Mt                   0.036491
Ewltp (g/km)         0.013687
W (mm)               0.009539
Mh                   0.004618
IT                   0.003585
ep (KW)              0.003427
Ft                   0.002169
Country_DE           0.000938
Ct_N1G               0.000295
Fuel consumption     0.000173
Ct_M1                0.000067
Ct_M1G               0.000000
Ct_N1                0.000000

In [9]:
#Classification_RandomForest
from sklearn import ensemble

rf_clf = ensemble.RandomForestClassifier(n_jobs=-1,random_state=123)
rf_clf.fit(X_train_c,y_train_c)

y_pred_c = rf_clf.predict(X_test_c)
pd.crosstab(y_test_c,y_pred_c,rownames=['RÃ©alitÃ©'],colnames=['PrÃ©diction'])

PrÃ©diction       A       B       C       D      E      F     G
RÃ©alitÃ©
A           112114       8       7       8      9      6     0
B                5  134887     537       0      7      0     0
C                0     497  241150     487     63     18    17
D                6       0     518  118542    239      2     0
E                3       0      43     279  62518    109     6
F               10       0      56       2    110  24981    20
G                3       0      41       0      3     37  8369

In [8]:
#Calculs des scores
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

accuracy = accuracy_score(y_test_c, y_pred_c)
print(f"Accuracy: {accuracy:.4f}")
print("/n")
precision = precision_score(y_test_c, y_pred_c, average='weighted')
print(f"Precision: {precision:.4f}")
print("/n")
recall = recall_score(y_test_c, y_pred_c, average='weighted')
print(f"Recall: {recall:.4f}")
print("/n")
f1 = f1_score(y_test_c, y_pred_c, average='weighted')
print(f"F1 Score: {f1:.4f}")
print("/n")
conf_matrix = confusion_matrix(y_test_c, y_pred_c)
print("Confusion Matrix:")
print(conf_matrix)
print("/n")
class_report = classification_report(y_test_c, y_pred_c)
print("Classification Report:")
print(class_report)

Accuracy: 0.9955
/n
Precision: 0.9955
/n
Recall: 0.9955
/n
F1 Score: 0.9955
/n
Confusion Matrix:
[[112114      8      7      8      9      6      0]
 [     5 134887    537      0      7      0      0]
 [     0    497 241150    487     63     18     17]
 [     6      0    518 118542    239      2      0]
 [     3      0     43    279  62518    109      6]
 [    10      0     56      2    110  24981     20]
 [     3      0     41      0      3     37   8369]]
/n
Classification Report:
              precision    recall  f1-score   support

           A       1.00      1.00      1.00    112152
           B       1.00      1.00      1.00    135436
           C       1.00      1.00      1.00    242232
           D       0.99      0.99      0.99    119307
           E       0.99      0.99      0.99     62958
           F       0.99      0.99      0.99     25179
           G       0.99      0.99      0.99      8453

    accuracy                           1.00    705717
   macro avg       1.00      0.99      0.99    705717
weighted avg       1.00      1.00      1.00    705717

In [10]:
#Feature importance
feats = {}
for feature, importance in zip(data_3.columns, rf_clf.feature_importances_):
    feats[feature] = importance 
    
importances = pd.DataFrame.from_dict(feats, orient='index').rename(columns={0: 'Importance'})
importances.sort_values(by='Importance', ascending=False)

                     Importance
Erwltp (g/km)      4.504036e-01
Mt                 1.179590e-01
At1 (mm)           1.017637e-01
ec (cm3)           1.016012e-01
Ft                 5.812912e-02
W (mm)             4.762984e-02
Ewltp (g/km)       3.654923e-02
IT                 3.496104e-02
Mh                 2.101868e-02
ep (KW)            2.081950e-02
Ct_N1G             3.248136e-03
Country_DE         2.707925e-03
Ct_M1              1.659498e-03
Fuel consumption   1.548663e-03
Ct_M1G             5.707392e-07
Ct_N1              2.540732e-07

In [6]:
#GradientBoostingClassifier
from sklearn.ensemble import GradientBoostingClassifier

gb_classifier = GradientBoostingClassifier(random_state=123)
gb_classifier.fit(X_train_c, y_train_c)

y_pred_c = gb_classifier.predict(X_test_c)
pd.crosstab(y_test_c,y_pred_c,rownames=['RÃ©alitÃ©'],colnames=['PrÃ©diction'])

KeyboardInterrupt:

In [ ]:
#Calculs des scores
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

accuracy = accuracy_score(y_test_c, y_pred_c)
print(f"Accuracy: {accuracy:.4f}")
print("/n")
precision = precision_score(y_test_c, y_pred_c, average='weighted')
print(f"Precision: {precision:.4f}")
print("/n")
recall = recall_score(y_test_c, y_pred_c, average='weighted')
print(f"Recall: {recall:.4f}")
print("/n")
f1 = f1_score(y_test_c, y_pred_c, average='weighted')
print(f"F1 Score: {f1:.4f}")
print("/n")
conf_matrix = confusion_matrix(y_test_c, y_pred_c)
print("Confusion Matrix:")
print(conf_matrix)
print("/n")
class_report = classification_report(y_test_c, y_pred_c)
print("Classification Report:")
print(class_report)

In [ ]:
#Feature importance
feats = {}
for feature, importance in zip(data_3.columns, gb_classifier.feature_importances_):
    feats[feature] = importance 
    
importances = pd.DataFrame.from_dict(feats, orient='index').rename(columns={0: 'Importance'})
importances.sort_values(by='Importance', ascending=False)

In [ ]:
#Regression_KNN
from sklearn.neighbors import KNeighborsRegressor

knn_regressor = KNeighborsRegressor(n_neighbors=3)
knn_regressor.fit(X_train_r, y_train_r)

y_pred_r = knn_regressor.predict(X_test_r)
pd.crosstab(y_test_r,y_pred_r,rownames=['RÃ©alitÃ©'],colnames=['PrÃ©diction'])

In [ ]:
#Calculs des scores
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y_test_r, y_pred_r)
print(f"Mean Squared Error (MSE): {mse:.4f}")
print("/n")
rmse = np.sqrt(mse)
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print("/n")
mae = mean_absolute_error(y_test_r, y_pred_r)
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print("/n")
r2 = r2_score(y_test_r, y_pred_r)
print(f"R-squared (R2): {r2:.4f}")

In [ ]:
#Feature importance
feats = {}
for feature, importance in zip(data_3.columns, knn_regressor.feature_importances_):
    feats[feature] = importance 
    
importances = pd.DataFrame.from_dict(feats, orient='index').rename(columns={0: 'Importance'})
importances.sort_values(by='Importance', ascending=False)

In [7]:
#Regression_DecisionTreeRegressor
from sklearn.tree import DecisionTreeRegressor

dtc_regressor = DecisionTreeRegressor(random_state=123)
dtc_regressor.fit(X_train_r, y_train_r)

y_pred = regressor.predict(X_test_r)
pd.crosstab(y_test_r,y_pred_r,rownames=['RÃ©alitÃ©'],colnames=['PrÃ©diction'])

NameError: name 'X_train' is not defined

In [ ]:
#Calculs des scores
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y_test_r, y_pred_r)
print(f"Mean Squared Error (MSE): {mse:.4f}")
print("/n")
rmse = np.sqrt(mse)
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print("/n")
mae = mean_absolute_error(y_test_r, y_pred_r)
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print("/n")
r2 = r2_score(y_test_r, y_pred_r)
print(f"R-squared (R2): {r2:.4f}")

In [ ]:
#Feature importance
feats = {}
for feature, importance in zip(data_3.columns, dtc_regressor.feature_importances_):
    feats[feature] = importance 
    
importances = pd.DataFrame.from_dict(feats, orient='index').rename(columns={0: 'Importance'})
importances.sort_values(by='Importance', ascending=False)

In [ ]:
#Regression_GradientBoostingRegressor
from sklearn.ensemble import GradientBoostingRegressor

gb_regressor = GradientBoostingRegressor(random_state=123)
gb_regressor.fit(X_train_r, y_train_r)

y_pred = gb_regressor.predict(X_test_r)
pd.crosstab(y_test_r,y_pred_r,rownames=['RÃ©alitÃ©'],colnames=['PrÃ©diction'])

In [ ]:
#Calculs des scores
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y_test_r, y_pred_r)
print(f"Mean Squared Error (MSE): {mse:.4f}")
print("/n")
rmse = np.sqrt(mse)
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print("/n")
mae = mean_absolute_error(y_test_r, y_pred_r)
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print("/n")
r2 = r2_score(y_test_r, y_pred_r)
print(f"R-squared (R2): {r2:.4f}")

In [ ]:
#Feature importance
feats = {}
for feature, importance in zip(data_3.columns, gb_regressor.feature_importances_):
    feats[feature] = importance 
    
importances = pd.DataFrame.from_dict(feats, orient='index').rename(columns={0: 'Importance'})
importances.sort_values(by='Importance', ascending=False)